### Add employee
POST http://localhost:3000/add
Content-Type: application/json

{
  "name": "Alex",
  "surname": "Mahlangu",
  "age": 22,
  "salary": 8000
}

### View employee
GET http://localhost:3000/view/

### Update employee
PUT http://localhost:3000/update/
Content-Type: application/json

{
  "salary": 9500
}

### Delete employee
DELETE http://localhost:3000/delete/